version: '3.8'

services:
  polygone-node:
    build: .
    container_name: polygone-relay
    volumes:
      - polygone-data:/data
    ports:
      - "4001:4001"
    restart: always
    environment:
      - RUST_LOG=info

volumes:
  polygone-data:
